version: '3'

services:
  app_test:
    container_name: payment_gateway_test
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - api_test:/app/src/app/
    depends_on:
      - postgres_test
    networks:
      - payment_gateway_test_net

  postgres_test:
    image: postgres:latest
    container_name: payment_gateway_db_test_postgress
    environment:
      - POSTGRES_USER=${TEST_DB_USER}  
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
      - DATABASE_HOST=${TEST_DB_HOST} 
    ports:
      - '5555:5432'
    volumes:
      - database_postgres_test:/var/lib/postgresql/data
    networks:
      - payment_gateway_test_net

volumes:
  api_test:
  database_postgres_test:

networks:
  payment_gateway_test_net:
    driver: bridge